# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto

comment:
  show_carryforward_flags: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: auto
      - name_prefix: patch-
        type: patch
        target: auto
