/**:
  ros__parameters:
    ignore_tags: []
    # bit 0~1: Point property based on spatial position
    #   00: Normal
    #   01: High confidence level of the noise
    #   10: Moderate confidence level of the noise
    #   11: Low confidence level of the noise
    # bit 2~3: Point property based on intensity
    #   00: Normal
    #   01: High confidence level of the noise
    #   10: Moderate confidence level of the noise
    #   11: Reserved
    # bit 4~5: Return number
    #   00: return 0
    #   01: return 1
    #   10: return 2
    #   11: return 3
    # bit 6~7: Reserved
